server:
  port: ":8080"
  tmpPath: "/Users/anirudhjakati/Desktop/GollabEdit/tmp/"

database:
  username: "gollabedit"
  password: ""
  host: "localhost"
  port: "3306"
  dbname: "gollabedit"

aws:
  filesBucket: "gollabedit"

